### ISSUE TITLE
2.6.2 矩阵范数 有个公式好像打错了

### ISSUE THREAD

**Issue by felixchenfy** [jianzhu/dl-notes#4]
第24页的第二个公式, 
"U* A U=∧" 是不是应该改为 "U* A* A U=∧"?
以及在之后推导的时候好像并没有用到这个性质.  
截图如下:

![Selection_016](https://user-images.githubusercontent.com/22253529/66692355-42507f80-ec63-11e9-9076-6ae5b5daea06.png)

谢谢您分享这份很有帮助的笔记!

**Comment by jianzhu** [comment]
确实错了，谢谢您。

这个对角化公式在maxtrix l2 norm的后续推导中确实没有用上，当时写这个公式的时候应该是为了方便和前面的eigenvector/eigenvalue小节对照看的。
